# Generated by Django 4.1.4 on 2023-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_filepost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='file_hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
